Gusto/embedded-react-sdk

package.json
Adding urls to `package.json` for better integration with npmjs.com
=> chore: add repository urls to package.json

CHANGELOG.md, package.json
Bump the version for a release of the profile form validation fix.
=> chore: version bump for 0.4.1

docs/05/02/company-onboarding.md
This adds docs for the company document signer component.
=> docs: add docs for document signer

CHANGELOG.md, package-lock.json, package.json
=> chore: release v0.5.0

src/components/Common/InternalError/InternalError.module.scss, src/components/Common/InternalError/InternalError.tsx, src/i18n/en/common.json, src/types/i18next.d.ts
=> style: add styling to SDK internal error component

src/components/Company/Locations/LocationForm/LocationForm.tsx, src/components/Employee/EmployeeList/EmployeeList.tsx, src/components/Employee/EmployeeList/List.tsx
🤷 EmployeeList refactor to use speakeasy
=> chore: speakeasy refactor of employee list

src/components/Employee/Deductions/DeductionForm.tsx, src/components/Employee/Deductions/Deductions.tsx, src/components/Employee/Deductions/DeductionsList.tsx, src/components/Employee/Profile/Profile.tsx
=> refactor: switching Deductions component to speakeasy api

docs/05/02/company-onboarding.md
Adds documentation for company federal taxes.
=> chore: add documentation for company federal taxes

src/components/Company/PaySchedule/PaySchedule.test.tsx, src/components/Company/PaySchedule/PaySchedule.tsx, src/components/Company/PaySchedule/_parts/Edit.tsx, src/components/Company/PaySchedule/_parts/List.tsx, src/test/mocks/apis/payschedule.ts, src/test/mocks/fixtures/get-v1-companies-company_id-pay_schedules-preview.json, src/test/mocks/fixtures/get-v1-companies-company_id-pay_schedules.json, src/test/mocks/fixtures/post-v1-companies-company_id-pay_schedules.json, src/test/mocks/fixtures/put-v1-companies-company_id-pay_schedules-pay_schedule_id.json
This PR aims to refactor Pay Schedule to the Speakeasy client
Outstanding
- Cannot get a Post test to pass and return the proper event in ViTest while working in dev mode
=> refactor: migrate payschedule to speakeasy

src/components/Company/PaySchedule/PaySchedule.tsx
Missed getting a todo into #213 per @dmortal request. Following up with quick fix
=> chore: add todo for i18n awareness

.ladle/config.mjs, src/components/Common/Button/Button.stories.tsx, src/components/Common/CalendarDisplay/CalendarDisplay.stories.tsx, src/components/Common/Card/Card.stories.tsx, src/components/Common/DataView/DataView.stories.tsx, src/components/Common/DocumentViewer/DocumentViewer.stories.tsx, src/components/Common/Fields/AllFieldsDemo.stories.tsx, src/components/Common/Fields/CheckboxField/CheckboxField.stories.tsx, src/components/Common/Fields/CheckboxGroupField/CheckboxGroupField.stories.tsx, src/components/Common/Fields/ComboBoxField/ComboBoxField.stories.tsx, src/components/Common/Fields/ComboBoxField/index.ts, src/components/Common/Fields/NumberInputField/NumberInputField.stories.tsx, src/components/Common/Fields/SelectField/SelectField.stories.tsx, src/components/Common/Fields/TextInputField/TextInputField.stories.tsx, src/components/Common/UI/Checkbox/Checkbox.stories.tsx, src/components/Common/UI/CheckboxGroup/CheckboxGroup.stories.tsx, src/components/Common/UI/ComboBox/ComboBox.stories.tsx, src/components/Common/UI/FieldCaption/FieldCaption.stories.tsx, src/components/Common/UI/FieldDescription/FieldDescription.stories.tsx, src/components/Common/UI/FieldErrorMessage/FieldErrorMessage.stories.tsx, src/components/Common/UI/FieldLayout/FieldLayout.stories.tsx, src/components/Common/UI/Fieldset/Fieldset.stories.tsx, src/components/Common/UI/HorizontalFieldLayout/HorizontalFieldLayout.stories.tsx, src/components/Common/UI/NumberInput/NumberInput.stories.tsx, src/components/Common/UI/Select/Select.stories.tsx, src/components/Common/UI/TextInput/TextInput.stories.tsx, src/components/Company/Industry/Industry.stories.tsx, src/hooks/useContainerBreakpoints/useContainerBreakpoints.stories.tsx, src/welcome/Welcome.stories.tsx
Just created this tool which will help us test an entire form with different elements. Hoping this is just a simple tool we can use for fast validation of RHF changes as well as form wide style changes.
=> chore: add all fields demo story

package-lock.json, package.json, src/components/Base/Base.tsx, src/components/Employee/Compensation/Compensation.tsx, src/components/Employee/Compensation/Edit.tsx, src/components/Employee/Compensation/useCompensation.ts, src/components/Flow/EmployeeOnboardingFlow.test.tsx, src/i18n/en/Employee.Compensation.json, src/models/WA_RISK_CODES.ts, src/test/mocks/apis/company_federal_taxes.ts, src/test/mocks/apis/employees.ts, src/types/i18next.d.ts
Adding worker compensation coverage information for employee compensation component (Washington.state)
https://github.com/user-attachments/assets/7a581c59-1e90-448b-9836-c458004ad687
=> feat: adding support for minimum wage requirements in WA state

.github/workflows/ci.yaml, .github/workflows/publish.yaml, .github/workflows/unpublish.yaml
=> Switch to gusto-ubunut-default github runner

src/components/Company/DocumentSignerFlow/DocumentSignerFlow.tsx
This Pr changes default behavior of deocumentsignerflow if signatory exists - instead of taking user to the assign signatory form it directs them to document list, while still allowing to change signatory if they want.
https://github.com/user-attachments/assets/5945b54f-5bbf-4fba-9645-1be9eec9e27d
=> documentSignerFlow fix

src/contexts/ApiProvider/ApiProvider.tsx, src/contexts/GustoProvider/GustoProviderCustomUIAdapter.tsx
fixes https://gustohq.atlassian.net/browse/GWS-4966
=> [GWS-4966] Setting custom headers doesn't work

src/components/Employee/Compensation/Compensation.tsx, src/components/Employee/Compensation/Edit.tsx, src/components/Employee/Compensation/useCompensation.ts, src/shared/constants.ts
This PR is responsible for updating the Zod schema of Compensation to support the variability of rate.
=> fix: update comission zod schema

CHANGELOG.md, package-lock.json, package.json
This release contains the following changes
- Refactored employee flow components structure and improved organization within Employee namespace
- Added component-level dictionary override functionality for improved internationalization
- Updated state taxes component to support API-based validation messages
- Fixed commission Zod schema validation issues
- Fixed issue with headers not being passed properly through our API client
=> chore: release 0.8.2

src/components/Company/StateTaxes/StateTaxesForm/Actions.tsx, src/components/Company/StateTaxes/StateTaxesForm/StateTaxesForm.tsx
Zod validation failed for boolean values. Also adding loading state to submit button
=> fix: fixing state tax boolean validation

package-lock.json, package.json, src/components/Employee/Compensation/Compensation.tsx, src/components/Employee/EmployeeList/EmployeeList.tsx, src/components/Employee/EmployeeList/List.tsx, src/components/Employee/EmployeeList/useEmployeeList.ts, src/components/Employee/Profile/Profile.tsx, src/components/Employee/Profile/getEmployeeAddressForProfile.test.ts, src/components/Employee/Taxes/StateForm.tsx, src/components/Employee/Taxes/Taxes.tsx, src/components/Employee/Taxes/useTaxes.ts, src/shared/constants.ts, src/test/mocks/apis/employee_state_taxes.ts
This updates the react SDK embedded API version to the latest
https://github.com/user-attachments/assets/26f32944-d87a-4508-a542-21da7834b377
https://github.com/user-attachments/assets/467b5e94-4140-437d-a78b-415bc80ac9e3
https://github.com/user-attachments/assets/6930b97f-6330-491e-b27b-c98939d3d00e
=> chore: update embedded api version

package-lock.json, package.json, src/test/mocks/apis/payrolls.ts
This upgrades the embedded api to the latest version. It resolves an issue where employee taxes were not loading at all.
Employee taxes loading as expected
=> chore: upgrade embedded api version to 0.6.4

src/components/Employee/PaymentMethod/Split.tsx, src/components/Employee/PaymentMethod/usePaymentMethod.ts
https://gustohq.atlassian.net/browse/GWS-5140
Fixing paymentMethod split validatioln
=> fix: fixing split validation

src/components/Employee/OnboardingSummary/OnboardingSummary.tsx
Allowing employee name to have special characters in onboarding summary
=> fix: allowing special characters in user name

src/components/Employee/Deductions/Deductions.tsx
resetting deductions to correct state on cancel
=> fix: setting correct mode on deductions cancel

src/components/Contractor/PaymentMethod/PaymentMethod.test.tsx, src/test/mocks/apis/cotnractor_payment_method.ts, src/test/mocks/fixtures/get-v1-contractors-contractor_id-bank_accounts.json, src/test/mocks/fixtures/get-v1-contractors-contractor_id-payment_method.json, src/test/mocks/handlers.ts
=> test: contractor payment method tests

src/components/Employee/PaymentMethod/PaymentMethod.test.tsx, src/components/Employee/PaymentMethod/Split.tsx, src/components/Employee/PaymentMethod/usePaymentMethod.ts, src/i18n/en/Employee.PaymentMethod.json, src/types/i18next.d.ts
Adds unit tests for percentage split validation logic in PaymentMethod component. Tests ensure splits total exactly 100% and handle edge cases.
=> test: add PaymentMethod percentage validation tests

CHANGELOG.md, package-lock.json, package.json
=> chore: release v0.10.0

CHANGELOG.md, package-lock.json, package.json
=> chore: release v0.10.1

src/components/Contractor/Address/Address.test.tsx, src/components/Contractor/Address/Form.tsx, src/test/mocks/apis/contractor_address.ts, src/test/mocks/fixtures/get-v1-contractors-contractor_id-address.json, src/test/mocks/fixtures/put-v1-contractors-contractor_id-address.json, src/test/mocks/handlers.ts
Adds tests for Contractor.Address
=> chore: add contractor address tests

CHANGELOG.md, package-lock.json, package.json
=> chore: release v0.10.2

src/components/Contractor/List/index.tsx
Finishes out some final polishing for Contractor Table to keep it consistent with other components
=> GWS-4559 Polishing Contractor Table

src/components/Contractor/List/index.tsx
@serikjensen this one's for you
=> refactor: remove inline style

.docs/docs-lock.yml, .docs/src/lockfile/documentTreeBuilder.ts, .docs/src/preview/__tests__/server.test.ts, .docs/src/preview/favicon.svg, .docs/src/preview/index.html, .docs/src/preview/server.ts, .docs/src/preview/styles.css, .docs/src/preview/types.ts, .docs/src/shared/types.ts, package.json
This PR is responsible for creating a preview environment for our documentation in order to help generate a better live preview before submitting changes...
- Dark Mode / Light Mode to save your eyes
- Link to view current file in production readme
- Ability to read our lock file to build correct document hierarchy
=> chore: introduce preview environment for docs live

.github/workflows/publish.yaml, .github/workflows/unpublish.yaml
Adding RC support for publishing and the ability to unpublished specific versions.
=> chore: add rc release and unpublish workflow

CHANGELOG.md, package.json
=> chore: release 10.4.0

CHANGELOG.md, package.json
=> chore: release 0.10.5

package-lock.json, package.json, src/components/Common/OnboardingStatusBadge/index.tsx, src/components/Common/TaxInputs/TaxInputs.tsx, src/components/Company/StateTaxes/StateTaxesForm/StateTaxesForm.tsx, src/components/Employee/EmployeeList/EmployeeList.tsx, src/shared/constants.ts
This PR
* Updates the embedded api to the latest version to get a schema fix for state taxes
* Updates state tax inputs with fixes around `tax_rate` inputs which require a select enum
=> fix: upgrade embedded api and fix state tax input issues

CHANGELOG.md, package-lock.json, package.json
=> chore: release 0.10.6

CHANGELOG.md, package-lock.json, package.json
=> chore: release 0.10.7

CHANGELOG.md, package-lock.json, package.json
=> chore: release 0.11.0

CHANGELOG.md, package-lock.json, package.json
=> chore: release 0.11.2

src/components/Common/ReorderableList/ReorderableList.module.scss, src/components/Common/RequirementsList/RequirementsList.module.scss
Updates ReorderableList and RequirementsList to use new theme variables
https://github.com/user-attachments/assets/4d042d92-76b1-4297-895f-f82722909a07
https://github.com/user-attachments/assets/a58a891e-562d-4acf-b8fb-3f9aa6ce437d
=> feat: update reorderable list and requirements list theme vars

.github/dependabot.yml
Enable dependabots automatic pull request
=> Enable dependabots automatic pull request

docs/component-adapter/component-inventory.md, src/components/Common/UI/ProgressBar/ProgressBar.tsx, src/components/Common/UI/ProgressBar/ProgressBarTypes.ts, src/components/Contractor/OnboardingFlow/OnboardingFlow.tsx, src/components/Contractor/OnboardingFlow/OnboardingFlowComponents.tsx, src/components/Contractor/OnboardingFlow/onboardingStateMachine.ts, src/components/Flow/Flow.tsx, src/components/Flow/useFlow.ts, src/i18n/en/Contractor.ContractorList.json, src/types/i18next.d.ts
https://github.com/user-attachments/assets/f802960f-538f-4c1b-8e85-509f978f349c
=> feat: adding cta to a progress bar

CHANGELOG.md, package-lock.json, package.json
Patch release 0.13.1
- Patch release for bug fixes and improvements
=> Release 0.13.1

src/components/Payroll/PayrollHistory/PayrollHistory.stories.tsx, src/components/Payroll/PayrollHistory/PayrollHistoryPresentation.module.scss, src/components/Payroll/PayrollHistory/PayrollHistoryPresentation.tsx, src/i18n/en/payroll.payrollhistory.json, src/types/i18next.d.ts
Extracts the PayrollHistory presentation layer into reusable components for better separation of concerns.
- **PayrollHistoryPresentation.tsx** - Pure presentation component with props interface
- **PayrollHistoryPresentation.module.scss** - Responsive styling with proper header/dropdown layout
- **PayrollHistory.stories.tsx** - Storybook stories for component development
- **payroll.payrollhistory.json** - i18n translations
=> feat: PayrollHistory presentation layer

src/components/Common/DataView/DataCards/DataCards.test.tsx, src/components/Common/DataView/DataCards/DataCards.tsx, src/components/Common/DataView/DataTable/DataTable.test.tsx, src/components/Common/DataView/DataTable/DataTable.tsx, src/components/Common/DataView/DataView.stories.tsx, src/components/Common/DataView/DataView.tsx, src/components/Common/DataView/useDataView.ts, src/components/Common/UI/Table/Table.module.scss, src/components/Common/UI/Table/Table.stories.tsx, src/components/Common/UI/Table/Table.test.tsx, src/components/Common/UI/Table/Table.tsx, src/components/Common/UI/Table/TableTypes.ts
This PR adds comprehensive footer support to the DataView component ecosystem, allowing tables and card views to display totals, summaries, and other footer content.
All feedback has been addressed, build passes, and tests are comprehensive.
- ✅ **Footer support** for Table, DataTable, DataCards, and DataView components
- ✅ **Object-based footer API** with column key mapping for type safety
- ✅ **Bold styling** with visual separator for footer rows
- ✅ **TypeScript typed** footer API with column key validation
- ✅ **Responsive design**: table footer in desktop, footer card in mobile
- ✅ **Clean, explicit API** with only one footer format
- ✅ **Comprehensive test coverage** for all components
- ✅ **Proper React patterns** (no array indices as keys)
```tsx
footer: () => ({
jobTitle: …
```
=> feat: add comprehensive footer support to DataView components

CHANGELOG.md, package-lock.json, package.json
=> chore: release 0.13.2

docs/workflows-overview/run-payroll.md
This PR adds documentation for payroll history functionality.
=> docs: Add payroll history documentation

src/assets/icons/close.svg, src/components/Common/UI/Alert/Alert.module.scss, src/components/Common/UI/Alert/Alert.tsx
=> fix: apply system styles to alert UI

src/components/Common/DocumentViewer/DocumentViewer.tsx, src/components/Company/DocumentSigner/DocumentList/DocumentList.tsx, src/components/Company/Locations/LocationsList/List.tsx, src/components/Employee/Profile/Profile.tsx
Small bug fixes:
- DocumentViewer heading config and i18n
- DocumentList i18n  
- LocationsList stray br tag
- Profile component defaults
=> fix: heading config, i18n, stray br tag, plus defaults

src/components/Common/UI/Table/Table.tsx
Quick fix for text inside of tables
=> fix: update Text inside table cells to use span instead of div

src/components/Payroll/PayrollOverview/PayrollOverviewPresentation.tsx, src/i18n/en/Payroll.PayrollOverview.json, src/types/i18next.d.ts
=> feat: adding warning when employees are getting paid by check
