- src/components/Employee/Profile/HomeAddress.tsx
We were running into an issue with Profile form where validation was failing because self_onboarding was undefined which was causing validation to fail.
This removes the self_onboarding property from home address validation so that it is properly ignored when we are onboarding as self and the checkbox for self_onboarding is not present.
https://github.com/user-attachments/assets/76f50b5a-53fe-435f-b814-dcd4590d09b9
When it is selected, validation does not fire and form submits correctly
https://github.com/user-attachments/assets/48727c07-b130-4ed8-a5de-336ff4e10649
> fix: restore validation for self onboarding profile form

- package.json
- src/components/Common/TaxInputs/TaxInputs.tsx
- src/components/Company/DocumentSigner/DocumentList/Head.tsx
- src/components/Company/DocumentSigner/DocumentList/List.tsx
- src/components/Company/DocumentSigner/DocumentList/ManageSignatories.tsx
- src/components/Employee/EmployeeList/EmployeeList.test.tsx
- src/components/Employee/EmployeeList/EmployeeList.tsx
- src/components/Employee/EmployeeList/List.tsx
- src/components/Employee/Profile/Actions.tsx
- src/components/Employee/Profile/Profile.tsx
- src/components/Flow/StateMachines/employeeSelfOnboarding.ts
- src/contexts/ThemeProvider/ThemeProvider.tsx
- src/test/mocks/apis/homeAddresses.ts
- src/test/mocks/apis/typeHelpers.ts
- src/test/mocks/fixtures/company_location.ts
- tsconfig.json
For simple typescript errors I fixed them inline.
For more complicated ones I added a `@ts-expect-error` for us to go fix in a future PR so that we can get back to good as quickly as possible.
> chore: fix & elide typescript errors; error fail CI build

- src/components/Company/DocumentSigner/DocumentList/Actions.tsx
- src/components/Company/DocumentSigner/DocumentList/DocumentList.tsx
- src/components/Company/DocumentSigner/DocumentList/Head.tsx
- src/components/Company/DocumentSigner/DocumentList/List.tsx
- src/components/Company/DocumentSigner/DocumentList/ManageSignatories.tsx
- src/i18n/en/Company.DocumentList.json
- src/shared/constants.ts
- src/types/i18next.d.ts
This adds a continue action to the company document list.
https://github.com/user-attachments/assets/803e371c-1045-4496-b9ca-d0eeb2869f80
> feat: add continue button to company document list

- src/components/Company/AssignSignatory/InviteSignatory/InviteSignatory.test.tsx
- src/components/Company/AssignSignatory/InviteSignatory/InviteSignatory.tsx
- src/components/Company/AssignSignatory/SignatoryForm.tsx
- src/components/Company/DocumentSigner/DocumentList/DocumentList.test.tsx
- src/components/Company/DocumentSigner/DocumentList/ManageSignatories.test.tsx
- src/test/mocks/apis/company_forms.ts
- src/test/mocks/apis/company_signatories.ts
- src/test/mocks/handlers.ts
This adds some minimal test coverage for the manage signatories and invite signatories form.
> chore: add test coverage for manage signatories and invite signatories

- src/components/Common/SignatureForm/SignatureFormFields.tsx
- src/components/Company/AssignSignatory/CreateSignatory/CreateSignatory.test.tsx
- src/components/Company/DocumentSigner/SignatureForm/Form.tsx
- src/components/Company/DocumentSigner/SignatureForm/SignatureForm.test.tsx
- src/components/Employee/DocumentSigner/SignatureForm.tsx
- src/i18n/en/Company.SignatureForm.json
- src/i18n/en/Employee.DocumentSigner.json
- src/test/mocks/apis/company_forms.ts
- src/test/mocks/apis/company_signatories.ts
- src/types/i18next.d.ts
This adds the rest of the tests for company document signer. It provides coverage for the create signatory and signature form, primarily around ensuring events are correctly firing as expected.
> chore: add tests for create signatory and signature form

- docs/03/getting-started-1.md
This adds more documentation about configuring the backend proxy, especially around configuring it for recent updates to the IP address.
For further context, the IP address must be provided for form signing operations to be completed. We are unable to provide that as a client side lib so this is a partner ask when they are configuring their backend proxy.
We merged an update to ZP here https://github.com/Gusto/zenpayroll/pull/263939  to allow for the IP address to be supplied via a request header in a single place in the proxy. Here is an example of configuring it in our own proxy for GWS flows for the SDK https://github.com/Gusto/gws-flows/pull/2704
> docs: add ip address guidance for partners

- CHANGELOG.md
- package-lock.json
- package.json
Runs the release for 0.6.0. Note: be sure to check the changelog and verify that documentation around breaking changes makes sense.
> chore: release 0.6.0

- src/components/Company/FederalTaxes/FederalTaxes.tsx
This adds default values for the company federal tax form.
Note that we intentionally left out the EIN as a default value. EIN is considered PII and we don't want to encourage partners to supply it in the client. See full discussion in slack here: https://gustohq.slack.com/archives/C071WFJUNF5/p1742235181264329
https://github.com/user-attachments/assets/8e019d5a-d302-47f0-a7a7-6f43d94370ad
> feat: update company federal taxes to have default values

- package-lock.json
- package.json
- src/components/Company/AssignSignatory/AssignSignatory.tsx
- src/components/Company/AssignSignatory/AssignSignatorySelection.tsx
- src/components/Company/AssignSignatory/CreateSignatory/CreateSignatory.test.tsx
- src/components/Company/AssignSignatory/CreateSignatory/CreateSignatory.tsx
- src/components/Company/AssignSignatory/CreateSignatory/CreateSignatoryForm.tsx
- src/components/Company/AssignSignatory/InviteSignatory/InviteSignatory.tsx
- src/components/Company/AssignSignatory/InviteSignatory/InviteSignatoryForm.tsx
- src/components/Company/AssignSignatory/SignatoryForm.tsx
- src/components/Employee/Taxes/Taxes.tsx
This updates the assign signatory components to use speakeasy including the create and invite signatory forms.
https://github.com/user-attachments/assets/9bc68633-0953-42be-9533-c930ecaf1fcd
https://github.com/user-attachments/assets/49511b5c-ebb5-4554-bafe-e0e3d53c08bc
https://github.com/user-attachments/assets/44e5ff04-2895-4308-9972-19dc6c028c47
> chore: refactor assign signatory components to use speakeasy

- package-lock.json
- package.json
- src/components/Base/Base.tsx
- src/helpers/formattedStrings.test.ts
- src/helpers/formattedStrings.ts
This change does the following
- Enables error list to come from OpenAPI (Meta data needed to be updated)
- Adds error_key prefix to nested error list logic to create valid nested keys
- Introduced camelCaseToSnakeCase which will be used to convert from/to various cases
> fix: support nested error list returned from speakeasy client

- src/components/Common/Fields/TextInputField/TextInputField.stories.tsx
- src/components/Common/Fields/TextInputField/TextInputField.tsx
- src/components/Common/Fields/TextInputField/index.ts
- src/components/Common/Fields/hooks/useField.test.tsx
- src/components/Common/Fields/hooks/useField.ts
- src/components/Common/UI/FieldLayout/FieldLayout.module.scss
- src/components/Common/UI/FieldLayout/FieldLayout.stories.tsx
- src/components/Common/UI/FieldLayout/FieldLayout.test.tsx
- src/components/Common/UI/FieldLayout/FieldLayout.tsx
- src/components/Common/UI/FieldLayout/index.ts
- src/components/Common/UI/TextInput/TextInput.module.scss
- src/components/Common/UI/TextInput/TextInput.stories.tsx
- src/components/Common/UI/TextInput/TextInput.test.tsx
- src/components/Common/UI/TextInput/TextInput.tsx
- src/components/Common/UI/TextInput/index.ts
This PR creates the infrastructure for the work to decouple React Hook Form from our form inputs. It does the following:
* Creates a new FieldLayout component which can be reused for arranging label, description, and error text along with an input
* Creates a new TextInput component that is separated from React Hook Form dependencies
* Creates a new useField hook that allows us to easily access React Hook Form context and map React Hook Form values onto common input props
* Implements a TextInputField component that creates a React Hook Form connected version of the TextInput
You can inspect the new components on ladle
https://github.com/user-attachments/assets/74e7872b-b5ae-4460-95d3-c48d5f4769ad
There will be follow up work to integrate this new TextInputField component with our …
> feat: add infrastructure for decoupling React Hook Form from inputs

- src/components/Common/UI/Checkbox/Checkbox.tsx
- src/components/Common/UI/FieldLayout/FieldLayout.test.tsx
- src/components/Common/UI/FieldLayout/FieldLayout.tsx
- src/components/Common/UI/HorizontalFieldLayout/HorizontalFieldLayout.tsx
- src/components/Common/UI/NumberInput/NumberInput.tsx
- src/components/Common/UI/Select/Select.test.tsx
- src/components/Common/UI/Select/Select.tsx
- src/components/Common/UI/TextInput/TextInput.tsx
- src/helpers/getDataProps.test.ts
- src/helpers/getDataProps.ts
- src/types/Helpers.d.ts
This updates our UI form components to accept data attributes
* Any `data-` prefixed props are accepted
* data props are forwarded to the root of the field layout component
The following JSX
Results in
> feat: update UI form components to accept data props

- .ladle/helpers/ActionHandler.tsx
- .ladle/helpers/FormWrapper.tsx
- .ladle/helpers/LadleState.tsx
- src/components/Common/Fields/CheckboxField/CheckboxField.stories.tsx
- src/components/Common/Fields/NumberInputField/NumberInputField.stories.tsx
- src/components/Common/Fields/SelectField/SelectField.stories.tsx
- src/components/Common/Fields/TextInputField/TextInputField.stories.tsx
- src/components/Common/UI/Checkbox/Checkbox.stories.tsx
- src/components/Common/UI/NumberInput/NumberInput.stories.tsx
- src/components/Common/UI/Select/Select.stories.tsx
- src/components/Common/UI/TextInput/TextInput.stories.tsx
This PR Aims to do the following
- Centralize `action` calls into a helper utility for FormFields
- Centralize `action` calls into a helper utility for Input's w/o React Hook Forms
- Update existing stories to take advantage of these improvements
> chore: centralize ladle actions for form components

- .ladle/helpers/FormWrapper.module.scss
- .ladle/helpers/FormWrapper.tsx
- .ladle/helpers/LadleState.tsx
- src/components/Common/Fields/CheckboxGroupField/CheckboxGroupField.stories.tsx
- src/components/Common/Fields/CheckboxGroupField/CheckboxGroupField.tsx
- src/components/Common/Fields/CheckboxGroupField/index.ts
- src/components/Common/UI/CheckboxGroup/CheckboxGroup.stories.tsx
- src/components/Common/UI/CheckboxGroup/CheckboxGroup.test.tsx
- src/components/Common/UI/CheckboxGroup/CheckboxGroup.tsx
- src/components/Common/UI/CheckboxGroup/index.ts
- src/components/Common/UI/FieldCaption/FieldCaption.module.scss
- src/components/Common/UI/FieldCaption/FieldCaption.stories.tsx
- src/components/Common/UI/FieldCaption/FieldCaption.tsx
- src/components/Common/UI/FieldCaption/index.ts
- src/components/Common/UI/FieldDescription/FieldDescription.module.scss
- src/components/Common/UI/FieldErrorMessage/FieldErrorMessage.module.scss
- src/components/Common/UI/FieldErrorMessage/FieldErrorMessage.tsx
- src/components/Common/UI/FieldLayout/FieldLayout.tsx
- src/components/Common/UI/Fieldset/Fieldset.module.scss
- src/components/Common/UI/Fieldset/Fieldset.stories.tsx
- src/components/Common/UI/Fieldset/Fieldset.test.tsx
- src/components/Common/UI/Fieldset/Fieldset.tsx
- src/components/Common/UI/Fieldset/index.ts
- src/components/Common/UI/HorizontalFieldLayout/HorizontalFieldLayout.module.scss
- src/hooks/useForkRef/index.ts
- src/hooks/useForkRef/useForkRef.test.tsx
- src/hooks/useForkRef/useForkRef.ts
This PR adds a CheckboxGroup component separated from React Hook Form. It also
* Implements a reusable Fieldset component which manages the layout concerns for checkbox group (and eventually radio group)
* Breaks out FieldCaption for consistent styling with label/legend
* Implements a connected React Hook Form version of CheckboxGroup with CheckboxGroupField
Values correctly updating for hook form
https://github.com/user-attachments/assets/3b6909c1-5af0-4dae-93fe-8db82f1f022a
Focus correctly being managed for the first checkbox input (will focus the first input in the group when the submission fails)
https://github.com/user-attachments/assets/0700dad4-36fa-47b5-a1e5-377a4abd68ff
> feat: add CheckboxGroup separated from react hook form

- src/components/Common/Fields/SelectField/SelectField.stories.tsx
- src/components/Common/Fields/SelectField/SelectField.tsx
- src/components/Common/Fields/hooks/useField.ts
- src/components/Common/UI/Select/Select.tsx
- src/components/Common/UI/Select/index.ts
This PR updates SelectField to have `options` instead of `items` + `children` for the API. It also updates to add an `inputRef` prop to the select field.
Field stories working using the options prop and firing the correct values for the form
https://github.com/user-attachments/assets/af75bd86-d868-4bd3-a948-79ab627b7501
inputRef working
https://github.com/user-attachments/assets/7a4d384c-eb29-4c99-9b7f-83a5a4a6dab9
> chore: update Select and SelectField to have consistent API for options

- .github/workflows/publish.yaml
It was removed here https://github.com/Gusto/embedded-react-sdk/pull/218/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
It looks like we can just run `build` since the openapi part of `generate` is no longer necessary and `build` runs the `i18n:generate` step
> build: remove deprecated `generate` step from publishing

- src/components/Base/Base.tsx
This PR aims to fix GWS-4366 which shows that errors do not clear from our `fieldErrors` list upon a successful submission. Simply clearing the list before the 2nd submit will handle this issue.
> fix: clear out error list before base submit handler fires to prevent errors from persisting

- .github/workflows/ci.yaml
- package-lock.json
- package.json
- src/components/Common/UI/Switch/Switch.test.tsx
- vite.config.ts
Opting to use a vite plugin here instead of `tsc` to reduce the number of passes & keep dev/build times low.
> Run typecheck through vite as part of bulild process

- src/components/Common/Fields/CheckboxGroupField/CheckboxGroupField.stories.tsx
- src/components/Common/Fields/CheckboxGroupField/CheckboxGroupField.tsx
- src/components/Common/Fields/ComboBoxField/ComboBoxField.stories.tsx
- src/components/Common/Fields/ComboBoxField/ComboBoxField.tsx
- src/components/Common/Fields/ComboBoxField/index.ts
- src/components/Common/Fields/RadioGroupField/RadioGroupField.stories.tsx
- src/components/Common/Fields/RadioGroupField/RadioGroupField.tsx
- src/components/Common/Fields/SelectField/SelectField.stories.tsx
- src/components/Common/Fields/SelectField/SelectField.tsx
- src/components/Common/Fields/SelectField/index.ts
- src/components/Common/Fields/hooks/useStringifyGenericFieldValue.test.tsx
- src/components/Common/Fields/hooks/useStringifyGenericFieldValue.ts
- src/components/Common/TaxInputs/TaxInputs.tsx
- src/components/Common/UI/CheckboxGroup/CheckboxGroupTypes.ts
- src/components/Common/UI/RadioGroup/RadioGroupTypes.ts
- src/components/Common/UI/Select/Select.module.scss
- src/components/Common/UI/Select/SelectTypes.ts
- src/components/Common/UI/Switch/Switch.tsx
- src/components/Employee/PaymentMethod/Split.tsx
- src/components/Employee/Taxes/StateForm.tsx
This PR updates our field components to support generic values. This was necessary for our field components to work with the state tax forms.
This change takes place in the field components instead of the UI components directly. This is because we want to make the contract between us and consumers as simple as possible. This makes it so that for components with options, they just support a consistent case with a string value and options that will have a string value inside corresponding. We take on all the complexity of managing generic types and ensuring that they map to string values.
This PR centralizes that logic inside of a hook and applies it to each component where generic values make sense including
* RadioGroupField
* CheckboxGroupField
* ComboBoxField
* SelectField
This also …
> feat: update field components to support generic values

- src/components/Employee/Profile/Profile.tsx
- src/components/Employee/Profile/getEmployeeAddressForProfile.test.ts
- src/components/Employee/Profile/getEmployeeAddressForProfile.ts
For self onboarding, we were experiencing an "Effective date is required" issue for users under the following circumstances
* They are invited to self onboard
* Their admin has filled out the compensation step
* They have submitted their profile with their address
* They refresh the flow and start from the beginning
Under the above circumstances, users were getting an error for "Effective date is required" when attempting to submit a profile update and were blocked from continuing the flow.
This PR provides a fix by ensuring an address is supplied when present even if it is not necessarily active. This ensures that the address is updated properly.
* This issue was occurring because we were filtering all addresses out by active
* Address being active is determined by if the effective date …
> fix: allow for non active fallback address in profile for self onboard

- src/components/Common/UI/Link/LinkTypes.ts
React Aria Link does not actually accept onClick even though it is supported by native `a` tags. Because we are still using React Aria Link, this updates to just remove it from the component API for now.
This wasn't getting caught for some reason due to using the spread operator. When destructuring onClick directly, it gets the error as expected. This merits more investigation into tsc on various machines and why we are seeing inconsistencies.
> chore: update to no longer have onClick with Link

- src/components/Common/DataView/DataView.stories.tsx
- src/components/Common/UI/Card/Card.stories.tsx
- src/components/Common/UI/Table/Table.stories.tsx
- src/components/Company/Locations/LocationsList/List.tsx
- src/components/Company/PaySchedule/_parts/List.tsx
- src/components/Employee/Compensation/List.tsx
- src/components/Employee/Deductions/DeductionsList.tsx
- src/components/Employee/EmployeeList/List.tsx
- src/components/Employee/PaymentMethod/BankAccountsList.tsx
- src/contexts/ComponentAdapter/ComponentsProvider.tsx
- src/contexts/ComponentAdapter/adapters/internalComponentAdapter.tsx
- src/contexts/ComponentAdapter/componentAdapterTypes.ts
- src/contexts/ComponentAdapter/useComponentContext.ts
- src/contexts/GustoProvider/GustoProvider.tsx
- src/contexts/GustoProvider/GustoProviderCustomUIAdapter.tsx
- src/contexts/index.ts
- src/contexts/index.tsx
This PR updates to surface exports needed to implement the adapter pattern locally. This includes exposing exports for
* ComponentContextType
* All UI component types
* GustoProvider and GustoProviderCustomUIAdapter
This also takes care of updating HamburgerMenu to just get imported from the common directory instead of implementing it as an internal component for component context. This internal component implementation was not necessary since we can just import these components from the common directory instead of getting them from context.
> chore: surface component adapter interfaces

- CHANGELOG.md
- package-lock.json
- package.json
This PR is for our 0.8.0 release. See CHANGELOG for detailed changes.
> chore: release 0.8.0

- src/components/Common/FieldLayout/FieldLayoutTypes.ts
- src/components/Common/UI/Alert/Alert.tsx
- src/components/Common/UI/Alert/AlertTypes.ts
- src/components/Common/UI/Badge/BadgeTypes.ts
- src/components/Common/UI/Button/ButtonTypes.ts
- src/components/Common/UI/CalendarPreview/CalendarPreviewTypes.ts
- src/components/Common/UI/Card/CardTypes.ts
- src/components/Common/UI/Checkbox/CheckboxTypes.ts
- src/components/Common/UI/CheckboxGroup/CheckboxGroupTypes.ts
- src/components/Common/UI/ComboBox/ComboBoxTypes.ts
- src/components/Common/UI/DatePicker/DatePickerTypes.ts
- src/components/Common/UI/Heading/HeadingTypes.ts
- src/components/Common/UI/Link/LinkTypes.ts
- src/components/Common/UI/Menu/MenuTypes.ts
- src/components/Common/UI/NumberInput/NumberInputTypes.ts
- src/components/Common/UI/ProgressBar/ProgressBarTypes.ts
- src/components/Common/UI/Radio/RadioTypes.ts
- src/components/Common/UI/RadioGroup/RadioGroupTypes.ts
- src/components/Common/UI/Select/SelectTypes.ts
- src/components/Common/UI/Switch/SwitchTypes.ts
- src/components/Common/UI/Table/TableTypes.ts
- src/components/Common/UI/Text/TextTypes.ts
- src/components/Common/UI/TextInput/TextInputTypes.ts
This adds props documentation to all adapter interfaces.
Note: this one is based on https://github.com/Gusto/embedded-react-sdk/pull/316 and will be merged after that one.
> Add documentation to adapter interfaces

- src/components/Employee/Compensation/useCompensation.ts
- src/components/Employee/PaymentMethod/BankAccount.ts
- src/components/Employee/PaymentMethod/usePaymentMethod.ts
- src/components/Employee/Profile/AdminPersonalDetails.tsx
- src/components/Employee/Profile/PersonalDetailsInputs.tsx
- src/components/Employee/Profile/SelfPersonalDetails.tsx
- src/components/Employee/Taxes/Taxes.tsx
- src/helpers/validations.ts
This PR contains updates to our ZOD Schema
Overview
- Replaced spreads of Zod Shapes to use Merge/Extend which is provided by Zod and allows for better management of schemas
- Removed error messages which were added to Zod by AI but are already configured in other parts of the app. Zod schemas can run i18n yet (Nor could Valibot)
> fix: update zod schemas to not spread but use merge/extend instead

- package.json
- src/components/Company/DocumentSignerFlow/SignatureForm/SignatureForm.tsx
- src/components/Company/Industry/Industry.tsx
- src/components/Company/Locations/LocationForm/LocationForm.tsx
- src/components/Company/PaySchedule/PaySchedule.tsx
- src/components/Employee/Compensation/Compensation.tsx
- src/components/Employee/Deductions/Deductions.tsx
- src/components/Employee/DocumentSigner/SignatureForm/SignatureForm.tsx
- src/components/Employee/EmployeeList/EmployeeList.tsx
- src/components/Employee/PaymentMethod/PaymentMethod.tsx
- src/components/Employee/Profile/Profile.tsx
- src/contexts/ApiProvider/ApiProvider.tsx
- src/contexts/GustoProvider/GustoProviderCustomUIAdapter.tsx
Since speakeasy marks react-query as a peerDependency and we have to include it in our bundle, this change moves custom provider from speakeasy to sdk.
> feat: moving ApiProvider into SDK from speakeasy client

- src/components/Employee/Taxes/StateForm.tsx
- src/components/Employee/Taxes/Taxes.tsx
This fix ensures Zod validation allows state taxes to be submitted, enabling us to receive more detailed error responses from the API.
The payload must pass initial validation before state tax data can be sent, which allows the API to return 422 responses with specific, descriptive errors related to state tax issues.
> fix: update state taxes to allow for API based validation messages

- src/components/Contractor/Address/Actions.tsx
- src/components/Contractor/Address/Address.tsx
- src/components/Contractor/Address/Form.tsx
- src/components/Contractor/Address/Head.tsx
- src/components/Contractor/Address/index.ts
- src/components/Contractor/Address/useAddress.ts
- src/components/Contractor/index.ts
- src/components/index.ts
- src/i18n/en/Contractor.Address.json
- src/shared/constants.ts
- src/types/i18next.d.ts
Adds the address form for contractors. See Figma here https://www.figma.com/design/6dxOSiONDiJoa9zY1wOwbs/Frontend-SDK-Partner-Design-File?node-id=8224-17639&t=O6iUevayceAZJvHb-4
https://github.com/user-attachments/assets/5ad81b0d-1948-409a-8ef4-7f629ffe4fe3
https://github.com/user-attachments/assets/d68da9db-d85e-4f9a-b05b-42663b6e0f21
https://github.com/user-attachments/assets/eb188534-e6fc-4fae-83f8-bd46f57dfd93
https://github.com/user-attachments/assets/97d9b079-419e-4cd1-b691-5c41cd37273c
> feat: add contractor address form

- src/components/Employee/Compensation/Compensation.test.tsx
- src/components/Employee/Compensation/Edit.tsx
- src/components/Employee/Compensation/useCompensation.ts
- src/i18n/en/Employee.Compensation.json
- src/types/i18next.d.ts
This PR updates compensation amount (rate) to no longer be labeled as optional since it is required by most employee types. It also updates the validation messages to correctly reflect the underlying validation logic in the schema (ex. provides an explanation if it is required, if the rate amount does not satisfy the min threshold etc)
Compensation amount is labeled as "optional" when it is actually required. Error message also simply says that the amount is required, it does not provide helpful context. Ex. in the video you can observe that the entered amount does not meet the min salary threshold. The validation message is just around the required field which is frustrating UX.
https://github.com/user-attachments/assets/eb02a468-c8cd-4618-8352-c8fdce03d958
Observe that
* Compensation …
> fix: update rate to not be labeled optional when it is required

- src/components/Employee/Profile/AdminPersonalDetails.tsx
- src/components/Employee/Profile/Profile.tsx
SSN validation was broken for employees that already had an SSN set. The field was failing validation when the user had an SSN but was editing the profile. In this case, SSN is undefined but we don't enable the validation so they can still proceed since they already have one set.
This PR fixes the validation. The root of the issue is that zod struggles to support nested discriminated unions. In this case we have enableSsn and selfOnboarding as different branches in the form validation. Attempting to nest discriminated unions results in a zod typing error. I was able to suppress the TS warnings using the typing solution [presented in this issue](https://github.com/colinhacks/zod/issues/1618#issuecomment-1511051340), however this still presented a failure for multiple keys with the same …
> fix: restore proper SSN validation

- CHANGELOG.md
- docs/03/01/authentication-1.md
- docs/03/getting-started-1.md
- docs/04/01/composition.md
- docs/04/01/event-handling.md
- docs/04/01/providing-your-own-data.md
- docs/04/01/routing.md
- docs/04/01/styles-and-theming.md
- docs/04/01/translation.md
- docs/05/workflows-overview.md
This PR
* Updates the changelog to include breaking changes around component renaming and flow component restructuring [introduced here](https://github.com/Gusto/embedded-react-sdk/pull/334)
* Updates docs to include updated references to `GustoProvider` instead of `GustoApiProvider`
* Removes documentation on block level customization (ex. Component.Head, Component.Body, Component.Actions etc) since that's a pattern we have opted to move away from
> chore: update changelog with breaking changes and update docs

- src/components/Employee/Deductions/DeductionForm.tsx
- src/components/Employee/Deductions/Deductions.test.tsx
This PR adds the `annualMaximum` field to the DeductionForm component and includes comprehensive test coverage.
- **13 comprehensive tests** covering all scenarios
- **100% coverage** of core business logic (`useDeductions.ts`)
- **Schema validation tests** for data transformation
- **Component integration tests**
- **Edge case handling** (null, zero, negative values)
https://github.com/user-attachments/assets/e8e147c9-acdf-4870-9c9b-838204b695c3
> feat: add annualmaximum field to deductionform with comprehensive tests

- src/components/Company/BankAccount/BankAccountComponents.tsx
- src/components/Company/BankAccount/BankAccountForm/Actions.tsx
- src/components/Company/BankAccount/BankAccountForm/BankAccountForm.test.tsx
- src/components/Company/BankAccount/BankAccountForm/BankAccountForm.tsx
- src/components/Company/BankAccount/BankAccountForm/context.ts
- src/components/Company/BankAccount/stateMachine.ts
- src/shared/constants.ts
This updates to add a cancel button for company bank account when you are navigating to the form from the list. Note that if you are hitting the form for the first time in the flow, the cancel doesn't show.
https://github.com/user-attachments/assets/5af50e32-46b0-4ad6-97da-0969907d8bcf
> feat: add cancel button for company bank account when editing

- src/components/Employee/Profile/Profile.tsx
- src/contexts/ApiProvider/ApiProvider.tsx
This is a bandage over existing issues where we do not correctly
invalidate the correct queries keys for each existing mutation
> invalidate queryCache after running mutation API

- src/components/Company/BankAccount/BankAccountForm/BankAccountForm.tsx
- src/components/Company/DocumentSigner/SignatureForm/SignatureForm.tsx
- src/components/Company/Industry/Industry.tsx
- src/components/Company/Locations/LocationForm/LocationForm.tsx
- src/components/Company/PaySchedule/PaySchedule.tsx
- src/components/Contractor/Address/Address.tsx
- src/components/Contractor/NewHireReport/NewHireReport.tsx
- src/components/Employee/Compensation/Compensation.tsx
- src/components/Employee/Deductions/Deductions.tsx
- src/components/Employee/DocumentSigner/SignatureForm/SignatureForm.tsx
- src/components/Employee/EmployeeList/EmployeeList.tsx
- src/components/Employee/PaymentMethod/PaymentMethod.tsx
- src/components/Employee/Profile/Profile.tsx
- src/components/Employee/Taxes/Taxes.tsx
Now that we automatically invalidate post mutation, we don't need to have all these manual invalidation call sites
> refactor: remove manual invalidation in favor of automatic invalidation after mutation

- src/components/Base/Base.tsx
- src/components/Company/BankAccount/BankAccountList/AccountView.tsx
- src/components/Company/Locations/LocationsList/List.tsx
- src/components/Employee/Taxes/FederalForm.tsx
- src/contexts/ComponentAdapter/componentAdapterTypes.ts
- src/contexts/GustoProvider/GustoProviderCustomUIAdapter.tsx
- src/contexts/LoadingIndicatorProvider/LoadingIndicatorProvider.tsx
- src/contexts/LoadingIndicatorProvider/useLoadingIndicator.tsx
This PR adds some updates that were needed while creating the latest partner adapter demo. This includes
* Exposing adapter types
* Updating to allow for setting the loading indicator on the provider globally so it doesn't have to be set on each individual component. it still defaults to the component level indicator if set, but allows consumers to set a global baseline
> feat: expose types for adapter and create a loading indicator provider

- .github/workflows/publish-rc.yaml
This allows specifying free form input for the branch you want to release when looking to run an RC release.
> chore: fix rc publish to allow branch selection

- src/components/Common/TaxInputs/TaxInputs.tsx
- src/components/Company/StateTaxes/StateTaxesForm/StateTaxesForm.tsx
- src/i18n/en/Company.StateTaxes.json
- src/types/i18next.d.ts
This PR makes the following updates for company state taxes:
* Updates tax_rate inputs to be of type TextInput instead of NumberInput. This is because the api can accept strings universally for these numeric values for tax rates but it can only accept numbers occasionally. There was no way to make the distinction with the api output so using strings was safer. We add `type="number"` to the text input component which prevents non numeric characters. Verified that the validation was working for a sampling of states and properly outputting an error message
* Updates validation messages to consistently output a more human readable required message (before they were saying things like "expected null but got boolean" etc
* Updates default values to correctly not set as strings for radios …
> fix: state tax fixes for tax_rate fields not submitting

- .ladle/adapters/PlainComponentAdapter.tsx
- src/components/Common/UI/Button/Button.module.scss
- src/components/Common/UI/Button/Button.stories.tsx
- src/components/Common/UI/Button/Button.test.tsx
- src/components/Common/UI/Button/Button.tsx
- src/components/Common/UI/Button/ButtonIcon.module.scss
- src/components/Common/UI/Button/ButtonIcon.stories.tsx
- src/components/Common/UI/Button/ButtonIcon.test.tsx
- src/components/Common/UI/Button/ButtonIcon.tsx
- src/components/Common/UI/Button/ButtonTypes.ts
- src/contexts/ThemeProvider/theme.ts
This PR reorganizes Button per design feedback as we were updating to use the new tokens
* Adds a tertiary button
* "error" is now one of the button variants along with primary, secondary, tertiary
* ButtonIcon now supports all button variants above (including tertiary which is the default) which allows icon button to take on the other button states. This one is also from design request
https://github.com/user-attachments/assets/b9f00236-c581-4d02-80c9-98c78ebc5508
> feat: update Button styling and variants

- src/components/Company/PaySchedule/PaySchedule.test.tsx
- src/components/Company/PaySchedule/PaySchedule.tsx
This feature will automatically change payschedule `mode` to `add` when pay schedule list has no entries.
> feat: navigate to add mode when payschedule list is empty

- src/components/Common/FieldCaption/FieldCaption.module.scss
- src/components/Common/FieldDescription/FieldDescription.module.scss
- src/components/Common/FieldErrorMessage/FieldErrorMessage.module.scss
- src/components/Common/FieldLayout/FieldLayout.module.scss
- src/components/Common/HorizontalFieldLayout/HorizontalFieldLayout.module.scss
- src/contexts/ThemeProvider/theme.ts
Updates the Field components to use the new theme variables
* FieldLayout
* FieldDescription
* FieldCaption
* FieldErrorMessage
* HorizontalFieldLayout
Adds new theme variables relating to inputs, since inputs are such a key part of the SDK and will likely get a lot of partner attention if the theming system is going to be viable.
https://github.com/user-attachments/assets/f7f6faf4-ec19-46f7-8a6d-e8cb16829510
https://github.com/user-attachments/assets/2d0371a6-b7ae-43d6-a866-5f88331b76ae
> feat: update field components to use new theme variables

- src/components/Common/UI/Alert/Alert.module.scss
This updates the Alert component to use new theme variables
> feat: update alert to use new theme variables

- src/components/Common/UI/Checkbox/Checkbox.module.scss
- src/components/Common/UI/CheckboxGroup/CheckboxGroup.module.scss
This PR updates Checkbox and CheckboxGroup to use new theme variables
> feat: update checkbox and checkboxgroup to use new theme variables

- src/components/Common/InternalError/InternalError.module.scss
- src/components/Common/Loading/Loading.module.scss
- src/components/Common/PaginationControl/PaginationControl.module.scss
This updates InternalError, Loading, and PaginationControl components to use the new theme variables.
https://github.com/user-attachments/assets/6fd4f794-3147-4921-9009-e72162ee73d7
https://github.com/user-attachments/assets/5aa81b1e-f6b7-4d0d-adc0-b6c554114ddb
> feat: update InternalError, Loading, and PaginationControl theme vars

- src/components/Base/Base.tsx
- src/components/Base/useBase.tsx
- src/components/Payroll/PayrollConfiguration/PayrollConfiguration.tsx
- src/components/Payroll/PayrollList/PayrollList.tsx
This updates the PayrollConfiguration component to use the prepare payroll endpoint instead of the get single payroll endpoint. This is because when we are editing payroll, we need to use the prepare endpoint first since the pay has not been calculated, see slack thread here: https://gustohq.slack.com/archives/C0327091JD8/p1757026541659839
This also updates the payroll list to only fetch unprocessed payrolls since we are currently working on the edit view.
Note that the gross pay has not been calculated when we use the prepare endpoint. This means that the gross pay is displaying as 0 for now. There is a separate ticket for this here https://gustohq.atlassian.net/browse/GWS-5505
https://github.com/user-attachments/assets/004055bc-ed06-41a5-aa39-af5eb2d8387a
> feat: update payroll configuration to use prepare endpoint

- package-lock.json
While checking for issues from yesterdays chalk(ish) securit issue, I found this in our `npm audit` that could easily be fixed.
> chore: updates from npm audit

- package-lock.json
- package.json
bumps embedded client to latest to fix missing QPs in GET payrolls API
embedded api client update here: https://github.com/Gusto/gusto-typescript-client/pull/73/files#diff-cbf1b5d477bbd44560629acaaf5720ee82847350bddb3c9df236ca454e372032 
ran `npm install @gusto/embedded-api@latest`
> chore: bumps embedded client to latest
